[book]
authors = ["sqyyy", "Skienex"]
language = "en"
src = "src"
title = "Liquip documentation"
description = "The Liquip-wiki covering the features of Liquip."

[output.html]
mathjax-support = true
site-url = "/docs-en/"
git-repository-url = "https://github.com/liquip/docs-en"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2